name: CI - AuthService

on:
  push:
    paths:
      - 'AuthService.*/**'
      - '.github/workflows/ci-auth.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore AuthService.API/AuthService.API.csproj

      - name: Build
        run: dotnet build AuthService.API/AuthService.API.csproj --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal
